f = open("text1.txt","w+")
f.write("Hello this is frist input\n")
f.close()
f = open("text1.txt","a")
f.write("Hello this is second input input")
f.close()
f = open("text1.txt","r")
print(f.read())
f.close()