f = open("D:\\Coding\\Python\\Python-Programing\\Assignments\\Assignmnet 7\\Assignmnet7.7.txt","w+")
f.write("Hello this is frist input\n")
f.close()
f = open("D:\\Coding\\Python\\Python-Programing\\Assignments\\Assignmnet 7\\Assignmnet7.7.txt","a")
f.write("Hello this is second input")
f.close()
f = open("D:\\Coding\\Python\\Python-Programing\\Assignments\\Assignmnet 7\\Assignmnet7.7.txt","r")
print(f.read())
f.close()